"""
M2: converts the binary data files (weights.bin, cmudict.bin,
dictionary_model.bin, and the chosen quantized .tflite exports) into C++
headers for src/TinyTTS/data/.

TinyTTS.h itself does not embed or auto-include this data -- it's shipped as
example/reference model data for convenience (include "TinyTTS/Data.h" and
call tts.setWeights()/setDictionary()/set*Model() before begin(), see
examples/tts_i2s_output/). Regenerate into a different location if you want
a different checkpoint/quantization/dictionary that isn't meant to ship as
part of the library. File names and variable names are all prefixed
`default_` to make clear this is just the shipped example data set, not
something TinyTTS.h treats specially.

Uses octal-escaped string-literal encoding ("\\ooo" per byte, always exactly
3 digits so there's no ambiguity about how many characters an escape
consumes -- unlike hex escapes, which are unbounded), NOT a comma-separated
integer initializer list. This matters a lot in practice: GCC's handling of
huge brace-init-lists scales badly (a 261KB comma-list header took ~4.2s to
compile with the Xtensa cross-compiler; the same data as a string literal
took ~0.84s -- and the gap widens further, not staying proportional, as the
data gets bigger). The full ~7MB combined data set timed out past 600s with
the comma-list encoding; switching to string literals fixed it.
"""
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # TinyTTS/


def to_header(path, out_path, varname, comment):
    data = open(path, "rb").read()
    with open(out_path, "w") as f:
        f.write(comment)
        f.write("#pragma once\n#include <cstddef>\n#include <cstdint>\n\n")
        f.write("namespace tts_model_data {\n\n")
        f.write(f"inline const unsigned char {varname}[] =\n")
        line_bytes = 32
        for i in range(0, len(data), line_bytes):
            chunk = data[i : i + line_bytes]
            f.write('"' + "".join(f"\\{b:03o}" for b in chunk) + '"\n')
        f.write(";\n")
        f.write(f"inline const size_t {varname}_len = {len(data)};\n\n")
        f.write("}  // namespace tts_model_data\n")
    print(f"{out_path}: {len(data)} bytes -> {os.path.getsize(out_path)} byte header")


WEIGHTS_COMMENT = """// default_weights: the hand-written text_encoder (PhonemeEncoder) + flow
// attention weights, fp32, extracted from tronghieuit/tiny-tts's 1.618M-param
// checkpoint (backtracking/tiny-tts on the HuggingFace Hub) by
// research/export_weights_and_vectors.py. Named-tensor binary format, see
// WeightStore.h for the parser. Consumed by PhonemeEncoder and Flow
// directly -- NOT run through TFLite Micro, see the project plan for why
// (onnx2tf cannot convert this windowed relative-position attention module).
// Pass to tts.setWeights(default_weights, default_weights_len) before
// tts.begin().

"""

CMUDICT_COMMENT = """// default_cmudict: a compact binary form of the CMU Pronouncing Dictionary
// (123,463 word -> ARPAbet-phoneme entries, sourced from
// tronghieuit/tiny-tts's npm-package/cmudict.json), with symbol ids and
// stress tones pre-resolved against tiny_tts.text.symbols at export time --
// no string/symbol-table logic needed at runtime, just binary search.
// Works standalone -- does NOT require default_dictionary_model (see
// default_dictionary_model_data.h). If you ARE using default_dictionary_model
// and want a smaller dictionary instead, see default_cmudict_slim_data.h.
// Generated by research/export_cmudict.py. Consumed by CmuDict.h.
// Pass to tts.setDictionary(default_cmudict, default_cmudict_len) before
// tts.begin().

"""

CMUDICT_SLIM_COMMENT = """// default_cmudict_slim: the same CMU Pronouncing Dictionary as
// default_cmudict (see default_cmudict_data.h), but trimmed to only the
// words that default_dictionary_model (see default_dictionary_model_data.h)
// does NOT already predict correctly on its own -- much smaller than the
// full dictionary. REQUIRES default_dictionary_model to be wired in too
// (setDictionaryModel()) for the rest of real English words to still work;
// used alone, most dictionary lookups would silently fall through to this
// dictionary's "not found" path (character-level fallback) instead of a
// correct pronunciation. An alternative to default_cmudict, not a
// supplement to it -- use one or the other, matching whether you're also
// shipping default_dictionary_model. See docs/research.md and the
// top-level README's "Model data sizes" for the actual size numbers.
// Generated by research/export_cmudict.py (after
// research/compute_cmudict_exceptions.py). Consumed by CmuDict.h.
// Pass to tts.setDictionary(default_cmudict_slim, default_cmudict_slim_len)
// before tts.begin() -- INSTEAD OF default_cmudict, not in addition to it.

"""

DP_COMMENT = """// default_duration_predictor_model: duration_predictor.tflite, quantized to
// INT8 weights with INT16 activations, fixed 32-phoneme input window
// (TFLite Micro has no input-resize API, so this graph -- like the decoder
// below -- must be a fixed shape). Chosen over full INT8 (int8 activations)
// because it's near-lossless (cosine similarity 0.9999 vs. the float32
// reference) at negligible extra size cost -- see the project plan's
// quantization study. Runs through TFLite Micro (tflm_esp32), not
// hand-written C++, since this graph converts cleanly from ONNX (it has no
// attention).
// Pass to tts.setDurationPredictorModel(default_duration_predictor_model,
// default_duration_predictor_model_len, 32) before tts.begin() -- the 32
// must match the fixed phoneme window this model was exported for.

"""

DICTIONARY_MODEL_COMMENT = """// default_dictionary_model: the neural G2P fallback (see DictionaryModel.h)
// for words not in default_cmudict -- a from-scratch C++ port of the
// reference project's own g2p_predict.js (itself a port of the Python
// `g2p_en` package), verified bit-exact against both before being trusted
// (see research/g2p_reference_numpy.py, docs/research.md).
//
// OPTIONAL and NOT included by TinyTTS/Data.h's umbrella, unlike the other
// four -- default_cmudict alone (123,463 entries) already covers the large
// majority of real English words, and this model costs extra flash for
// better coverage of the remainder (proper nouns, made-up words, etc.) via
// plausible phonetic guessing instead of crude letter-by-letter fallback.
// See the top-level README's "Model data sizes" and docs/research.md for
// the actual size tradeoff against default_cmudict_slim (this model's size
// alone is not the full picture -- see default_cmudict_slim_data.h).
// #include this header explicitly (it's not pulled in by TinyTTS/Data.h)
// and pass to tts.setDictionaryModel(default_dictionary_model,
// default_dictionary_model_len) before tts.begin() if you want it.

"""

DECODER_COMMENT = """// default_decoder_model: decoder.tflite (the HiFi-GAN-style vocoder stage),
// full INT8 quantization (int8 weights, INT16 activations -- same scheme as
// duration_predictor), fixed 96-frame (~1.1s of audio at 44.1kHz) input
// window. This is the ONLY variant of the 4 studied that actually runs on
// TFLite Micro, confirmed with a host-side (x86, ASan) TFLM build of the
// real interpreter/allocator code, not just compiled-for-ESP32 and assumed:
//   - float16 weights: DEQUANTIZE kernel only accepts int8/int16/uint8
//     input, not float16 -- AllocateTensors() fails outright.
//   - dynamic-range (weights-only int8, float32 activations): TFLite Micro
//     does not support "hybrid" models at all ("Hybrid models are not
//     supported on TFLite Micro", from CONV_2D's own prepare step) --
//     AllocateTensors() fails outright.
//   - full INT8 with INT8 activations: loads fine, but measurably degrades
//     audio quality (12.4dB SNR, audible noise) vs. this variant's 22.6dB --
//     see the project plan's quantization study.
// (On real ESP32-S3 hardware, feeding either of the first two unsupported
// variants to tflm_esp32 didn't just fail cleanly -- AllocateTensors()'s
// failure path left the heap corrupted, surfacing later as a confusing TLSF
// assert on an unrelated allocation. That corruption is a tflm_esp32/TFLM
// robustness gap, not something callers can work around -- avoid it by
// simply not feeding it a hybrid or float16 model, as done here.)
// Also needs a decoder tensor arena of at least ~1.5MB (see
// TinyTTS::decoder_arena_size_ / setArenaSizes()) -- confirmed via the same
// host-side build.
// Pass to tts.setDecoderModel(default_decoder_model,
// default_decoder_model_len, 96) before tts.begin() -- the 96 must match
// the fixed frame window this model was exported for.

"""


def main():
    out_dir = os.path.join(BASE, "src", "TinyTTS", "data")
    os.makedirs(out_dir, exist_ok=True)

    to_header(
        os.path.join(BASE, "research", "weights.bin"),
        os.path.join(out_dir, "default_weights_data.h"),
        "default_weights",
        WEIGHTS_COMMENT,
    )
    to_header(
        os.path.join(BASE, "research", "cmudict.bin"),
        os.path.join(out_dir, "default_cmudict_data.h"),
        "default_cmudict",
        CMUDICT_COMMENT,
    )
    slim_path = os.path.join(BASE, "research", "cmudict_slim.bin")
    if os.path.exists(slim_path):
        to_header(
            slim_path,
            os.path.join(out_dir, "default_cmudict_slim_data.h"),
            "default_cmudict_slim",
            CMUDICT_SLIM_COMMENT,
        )
    else:
        print(f"skipping default_cmudict_slim_data.h -- {slim_path} not found "
              "(run export_cmudict.py after compute_cmudict_exceptions.py)")
    to_header(
        os.path.join(
            BASE,
            "research",
            "tflite_int8",
            "duration_predictor",
            "duration_predictor_full_integer_quant_with_int16_act.tflite",
        ),
        os.path.join(out_dir, "default_dp_model_data.h"),
        "default_duration_predictor_model",
        DP_COMMENT,
    )
    to_header(
        os.path.join(
            BASE, "research", "tflite_int8", "decoder", "decoder_full_integer_quant_with_int16_act.tflite"
        ),
        os.path.join(out_dir, "default_decoder_model_data.h"),
        "default_decoder_model",
        DECODER_COMMENT,
    )
    to_header(
        os.path.join(BASE, "research", "dictionary_model.bin"),
        os.path.join(out_dir, "default_dictionary_model_data.h"),
        "default_dictionary_model",
        DICTIONARY_MODEL_COMMENT,
    )


if __name__ == "__main__":
    main()
