#pragma once
// Convenience umbrella: #include "TinyTTS/Data.h" instead of the four
// individual data headers below. All four live in the `tts_model_data`
// namespace (default_weights, default_cmudict, default_duration_predictor_model,
// default_decoder_model, and their matching *_len constants) -- see each
// header's own comment for what it contains and which TinyTTS setter it
// belongs to.
//
// This is example/reference model data (generated by
// research/export_headers.py, see docs/research.md), shipped as part of
// the library for convenience -- but NOT included by TinyTTS.h itself, and
// NOT used unless your sketch explicitly includes this header and calls
// the setters (see examples/tts_i2s_output/). A sketch that doesn't need
// this particular model doesn't pay for it.
//
// Two more data headers exist but are deliberately NOT part of this
// umbrella -- they're alternatives/additions, not always-needed pieces:
//   - TinyTTS/data/default_dictionary_model_data.h (default_dictionary_model):
//     an OPTIONAL neural G2P fallback model for words not in the dictionary
//     (setDictionaryModel()) -- costs extra flash for better coverage.
//   - TinyTTS/data/default_cmudict_slim_data.h (default_cmudict_slim): a
//     smaller ALTERNATIVE to default_cmudict (use one or the other, not
//     both) that only works correctly if default_dictionary_model is also
//     wired in -- see that header's own comment for the actual size
//     tradeoff (it's not simply "smaller is better").
#include "TinyTTS/data/default_cmudict_data.h"
#include "TinyTTS/data/default_decoder_model_data.h"
#include "TinyTTS/data/default_dp_model_data.h"
#include "TinyTTS/data/default_weights_data.h"
